<h2>First Import Pandas Library And Assign Dataset Into Dataframe </h2>

In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\user\Downloads\COVID19_Statistics_200_Rows-1.csv")

df

,Record_ID,Date,Country,State,Confirmed,Recovered,Deaths,Active,Tests_Conducted,Vaccination_Rate_%
0,1,2021-01-02,USA,California,4107,3518,70,519,10528,99
1,2,2021-01-03,Brazil,Sao Paulo,112163,102717,2474,6972,438420,59
2,3,2021-01-04,Japan,Tokyo,220599,191161,5182,24256,469235,35
3,4,2021-01-05,UK,England,445177,347729,8113,89335,452508,73
4,5,2021-01-06,UK,England,241776,192943,3413,45420,312154,70
...,...,...,...,...,...,...,...,...,...,...
195,196,2021-07-16,Japan,Tokyo,115516,90567,1413,23536,118084,23
196,197,2021-07-17,Brazil,Sao Paulo,294730,227226,1002,66502,1186057,76
197,198,2021-07-18,Japan,Tokyo,53510,44179,58,9273,76248,47
198,199,2021-07-19,USA,California,157701,123045,4597,30059,468950,71
199,200,2021-07-20,India,Maharashtra,141681,123688,805,17188,539202,25

<h2>Second Split Date Column into Year, Month, Day </h2>

In [2]:
# First Change Date Datatype from object to date

df['Date'] = pd.to_datetime(df['Date'])

# Then split the date column 

df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day


print(df['Date'].dtype)   # should say datetime64[ns]
print(df['Month'].dtype)  # should say int32

datetime64[ns]
int32

In [3]:
#Change Month Column into Text instead of regular number

month_map = {
    1: 'January', 2: 'February', 3: 'March', 4: 'April',
    5: 'May', 6: 'June', 7: 'July', 8: 'August',
    9: 'September', 10: 'October', 11: 'November', 12: 'December'
}
df['Month_Name'] = df['Month'].map(month_map)

df

,Record_ID,Date,Country,State,Confirmed,Recovered,Deaths,Active,Tests_Conducted,Vaccination_Rate_%,Year,Month,Day,Month_Name
0,1,2021-01-02,USA,California,4107,3518,70,519,10528,99,2021,1,2,January
1,2,2021-01-03,Brazil,Sao Paulo,112163,102717,2474,6972,438420,59,2021,1,3,January
2,3,2021-01-04,Japan,Tokyo,220599,191161,5182,24256,469235,35,2021,1,4,January
3,4,2021-01-05,UK,England,445177,347729,8113,89335,452508,73,2021,1,5,January
4,5,2021-01-06,UK,England,241776,192943,3413,45420,312154,70,2021,1,6,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,2021-07-16,Japan,Tokyo,115516,90567,1413,23536,118084,23,2021,7,16,July
196,197,2021-07-17,Brazil,Sao Paulo,294730,227226,1002,66502,1186057,76,2021,7,17,July
197,198,2021-07-18,Japan,Tokyo,53510,44179,58,9273,76248,47,2021,7,18,July
198,199,2021-07-19,USA,California,157701,123045,4597,30059,468950,71,2021,7,19,July
199,200,2021-07-20,India,Maharashtra,141681,123688,805,17188,539202,25,2021,7,20,July

In [4]:
#The raw dataset was cleaned by removing rows where the Active column was 0 because these records violated the relationship: Confirmed = Active + Recovered + Deaths. Since the values were inconsistent, they were excluded to ensure the accuracy and reliability of the analysis.
#Assign the new cleaned dataset into new dataframe then save it

df_1 = df.drop(df[df["Active"]==0].index)

df_1.to_csv(r"C:\Users\user\Downloads\COVID19_Statistics_Cleaned.csv", index=False)